# Generated by Django 4.2.7 on 2025-07-12 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('aadhar_photo', models.ImageField(blank=True, null=True, upload_to='aadhar/')),
                ('is_verified', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('renter', 'Renter'), ('tourist', 'Tourist')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('location', models.CharField(default='Nainital', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='scooters/')),
                ('condition_notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('petrol_before', models.ImageField(blank=True, null=True, upload_to='petrol/')),
                ('petrol_after', models.ImageField(blank=True, null=True, upload_to='petrol/')),
                ('condition_before', models.TextField(blank=True)),
                ('condition_after', models.TextField(blank=True)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.scooter')),
            ],
        ),
    ]
