# Generated by Django 4.2.7 on 2025-07-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aadhar_photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
